name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        export:
          - { template: "Linux/X11", dir: "Linux", file: "x86_64" }
          - { template: "Windows Desktop", dir: "Windows", file: "exe" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.x
          
      - name: Cache Godot
        id: godot-cache
        uses: actions/cache@v3.2.2
        with:
          path: ./Godot_v4.0-beta9_mono_linux_x86_64/
          key: godot-cache
          
      - name: Download Godot
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: wget https://downloads.tuxfamily.org/godotengine/4.0/beta9/mono/Godot_v4.0-beta9_mono_linux_x86_64.zip
        
      - name: Extract Godot
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: unzip ./Godot_v4.0-beta9_mono_linux_x86_64.zip
        
      - name: Cache Export Templates
        id: templates-cache
        uses: actions/cache@v3.2.2
        with:
          path: /home/runner/.local/share/godot/export_templates/4.0.beta9.mono/
          key: templates-cache
          
      - name: Download Export Templates
        if: steps.templates-cache.outputs.cache-hit != 'true'
        run: wget https://downloads.tuxfamily.org/godotengine/4.0/beta9/mono/Godot_v4.0-beta9_mono_export_templates.tpz
        
      - name: Extract Export Templates
        if: steps.templates-cache.outputs.cache-hit != 'true'
        run: unzip ./Godot_v4.0-beta9_mono_export_templates.tpz
        
      - name: Create Export Template directory
        if: steps.templates-cache.outputs.cache-hit != 'true'
        run: mkdir /home/runner/.local/share/godot/export_templates/4.0.beta9.mono --parents
        
      - name: Copy Export Templates
        if: steps.templates-cache.outputs.cache-hit != 'true'
        run: cp ./templates/* /home/runner/.local/share/godot/export_templates/4.0.beta9.mono -r
        
      - name: Remove old Export Templates
        if: steps.templates-cache.outputs.cache-hit != 'true'
        run: rm ./templates -rf
        
      - name: Create Export directory
        run: mkdir "./Releases/${{ matrix.export.dir }}" --parents
      
      - name: Export for ${{ matrix.export.dir }} with Godot
        run: "\"./Godot_v4.0-beta9_mono_linux_x86_64/Godot_v4.0-beta9_mono_linux.x86_64\" --display-driver headless --export-release \"${{ matrix.export.template }}\" \"./Releases/${{ matrix.export.dir }}/Cosmos-Peddler.${{ matrix.export.file }}\""

      - name: Print directory
        run: ls "./Release/${{ matrix.export.dir }}/"

      - name: Upload ${{ matrix.export.dir }} artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cosmos-Peddler_${{ matrix.export.dir }}
          path: ./Releases/${{ matrix.export.dir }}/
