name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu
    strategy:
      matrix:
        export:
          - { template: "Linux/X11", file: "x86_64" }
          - { template: "Windows Desktop", file: "exe" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.1
          
      - name: Download Godot
        run: wget https://downloads.tuxfamily.org/godotengine/4.0/beta9/mono/Godot_v4.0-beta9_mono_linux_x86_64.zip
        
      - name: Extract Godot
        run: unzip ./Godot_v4.0-beta9_mono_linux_x86_64.zip
      
      - name: Export with Godot
        run: "\"./Godot_v4.0-beta9_mono_linux_x86_64/Godot_v4.0-beta9_mono_linux.x86_64\" --path ${{ env.GITHUB_WORKSPACE }} --export-release ${{ matrix.export.template }} \"./Releases/${{ matrix.export.template }}/Cosmos-Peddler.${{ matrix.export.file }}\""

      - name: Upload ${{ matrix.export.template }} artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cosmos-Peddler_${{ matrix.export.template }}
          path: Releases/${{ matrix.export.template }}
